[tool.poetry]
name = "nonebot-plugin-setu-collection"
version = "0.1.6"
description = ""
authors = ["KarisAya <1048827424@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
nonebot = "^1.9.1"
nonebot-adapter-onebot = "^2.4.2"
httpx = "^0.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
